#!/usr/bin/env python3

import pathlib
import os
from sys import argv

# Take in our command line arguments
inPath = argv[1]
oldPattern = argv[2]
newPattern = argv[3]


# Create a function that recursivly replaces all instances of a string
def replaceContents(path):
    # Get contents of directory
    dirContents = os.listdir(path)

    # Loop each content, if a directory call recursivly
    # If a file, take all contents and name and replace oldPattern with newPattern
    for i in dirContents:
        ultaPath = str(path) + "/" + i
        
        if os.path.isdir(ultaPath):
            replaceContents(ultaPath)
        
        else:
            file = open(ultaPath, "r")

            fileContents = file.read()
            newContents = fileContents.replace(oldPattern, newPattern)
            file.close()
            os.remove(ultaPath)

            newPath = str(path) + "/" + i.replace(oldPattern, newPattern)

            newFile = open(newPath, "w")
            newFile.write(newContents)
            newFile.close()



# Check to see if we recived enough arguments
if len(argv) < 3:
    print("Not enough arguments.")
    print("Correct format: replace <path> <oldPattern> <newPattern>")
    exit()


# Create a path and check if it exists
path = pathlib.Path(inPath)
if not os.path.exists(path):
    print("The entered path does not exist. Please try again with a valid path.")
    exit()

# Call our replace function
replaceContents(path)

